Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -14,7 +14,13 @@ jobs:
       uses: actions/checkout@v2
 
     - name: Decode service account key
-      run: echo "${{ secrets.GCP_SA_KEY_BASE64 }}" | base64 --decode > $HOME/gcloud-service-key.json
+      run: |
+        echo "${{ secrets.GCP_SA_KEY_BASE64 }}" | base64 --decode > $HOME/gcloud-service-key.json
+        if [ ! -s $HOME/gcloud-service-key.json ]; then
+          echo "Failed to create service account key file."
+          exit 1
+        fi
+        cat $HOME/gcloud-service-key.json  # Debug: Output the content of the file
 
     - name: Set GOOGLE_APPLICATION_CREDENTIALS
       run: echo "GOOGLE_APPLICATION_CREDENTIALS=$HOME/gcloud-service-key.json" >> $GITHUB_ENV
